# Generated by Django 3.2.4 on 2021-09-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CONSUMER', '소비자'), ('SUPERVISOR', '최고관리자')], default='SUPERVISOR', help_text='계정 유형', max_length=20),
        ),
    ]
