# Generated by Django 3.2.4 on 2021-09-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='내용')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='제목', max_length=100)),
                ('comment', models.TextField(help_text='내용', max_length=100)),
                ('photo', models.ImageField(upload_to='%Y/%m/%d')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
