# Generated by Django 3.2.4 on 2021-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchoices',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='지불가격'),
            preserve_default=False,
        ),
    ]
